replicaCount: 1

image:
  repository: node
  tag: "16"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
